apiVersion: v1
kind: PersistentVolume
metadata:
  name: quiz-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /tmp/quiz-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: too-big
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: ""
